apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: techdocs-example-one
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: pep8speaks-org/pep8speaks
    tags:
        - techdocs
        - example
spec:
    type: service
    lifecycle: test
    owner: any
    system: project-x

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    name: project-x
    description: Handy tools to keep artists in the loop
spec:
    owner: artist-relations-team
    domain: artists